// examples/solid-example/src/main.ts
import { createEsFluentRuntime } from "@es-fluent/core";
import { I18nProvider, useI18n } from "@es-fluent/solid";
import { createComponent, createEffect } from "solid-js";
import { render } from "@solidjs/web";

import "../../web-demo.css";
import { loadResource, manifest, messages } from "../generated/index.js";

const copy = messages["solid-example"]["solid-example"];
const runtime = createEsFluentRuntime({ manifest, loadResource });
const initial = await runtime.createRequest(navigator.languages);

function Demo(): HTMLElement {
  const i18n = useI18n();
  const main = document.createElement("main");
  main.className = "demo-shell";
  main.style.cssText =
    "--demo-glow:#14532d;--demo-accent:#115e59;--demo-highlight:#86efac;--demo-button:#bbf7d0";
  main.innerHTML = `
    <article class="demo-card">
      <p class="demo-kicker" data-copy="kicker"></p>
      <h1 class="demo-title" data-copy="title"></h1>
      <p class="demo-body" data-copy="body"></p>
      <section class="demo-messages" aria-live="polite">
        <p class="demo-message" data-copy="greeting"></p>
        <p class="demo-message" data-copy="inbox"></p>
      </section>
      <div class="demo-controls">
        <p class="demo-locale" data-copy="locale"></p>
        <button class="demo-button" type="button" data-action="locale"></button>
      </div>
    </article>
  `;

  const element = <T extends Element>(selector: string): T => {
    const value = main.querySelector<T>(selector);
    if (value === null) {
      throw new Error(`Solid demo element is missing: ${selector}`);
    }
    return value;
  };
  const kicker = element<HTMLElement>("[data-copy=kicker]");
  const title = element<HTMLElement>("[data-copy=title]");
  const body = element<HTMLElement>("[data-copy=body]");
  const greeting = element<HTMLElement>("[data-copy=greeting]");
  const inbox = element<HTMLElement>("[data-copy=inbox]");
  const locale = element<HTMLElement>("[data-copy=locale]");
  const localeButton = element<HTMLButtonElement>("[data-action=locale]");

  createEffect(
    () => {
      const activeLocale = i18n.locale();
      return {
        activeLocale,
        body: i18n.t(copy["demo_copy-Body"]),
        button: i18n.t(copy["demo_copy-SwitchLocale"]),
        greeting: i18n.t(copy.greeting, { name: "Lin" }),
        inbox: i18n.t(copy.inbox, { count: 3 }),
        kicker: i18n.t(copy["demo_copy-Kicker"]),
        locale: i18n.t(copy.locale_status, { locale: activeLocale }),
        pending: i18n.pending(),
        title: i18n.t(copy["demo_copy-Title"]),
      };
    },
    (localized) => {
      document.documentElement.lang = localized.activeLocale;
      kicker.textContent = localized.kicker;
      title.textContent = localized.title;
      body.textContent = localized.body;
      greeting.textContent = localized.greeting;
      inbox.textContent = localized.inbox;
      locale.textContent = localized.locale;
      localeButton.textContent = localized.button;
      localeButton.disabled = localized.pending;
    },
  );

  localeButton.addEventListener("click", () => {
    void i18n.setLocale(i18n.locale() === "fr" ? "en" : "fr");
  });
  return main;
}

const root = document.querySelector<HTMLElement>("#root");
if (root === null) {
  throw new Error("Solid demo root is missing");
}

render(
  () =>
    createComponent(I18nProvider, {
      runtime,
      initial,
      get children() {
        return createComponent(Demo, {});
      },
    }),
  root,
);

// examples/react-example/src/main.ts
import { createEsFluentRuntime } from "@es-fluent/core";
import { I18nProvider, useI18n } from "@es-fluent/react";
import { createElement, type CSSProperties, type ReactElement } from "react";
import { createRoot } from "react-dom/client";

import "../../web-demo.css";
import { loadResource, manifest, messages } from "../generated/index.js";

const copy = messages["react-example"]["react-example"];
const runtime = createEsFluentRuntime({ manifest, loadResource });
const initial = await runtime.createRequest(navigator.languages);

function Demo(): ReactElement {
  const i18n = useI18n();
  document.documentElement.lang = i18n.locale;

  return createElement(
    "main",
    {
      className: "demo-shell",
      style: {
        "--demo-glow": "#7f1d1d",
        "--demo-accent": "#9f1239",
        "--demo-highlight": "#fda4af",
        "--demo-button": "#fecdd3",
      } as CSSProperties,
    },
    createElement(
      "article",
      { className: "demo-card" },
      createElement(
        "p",
        { className: "demo-kicker" },
        i18n.t(copy["demo_copy-Kicker"]),
      ),
      createElement(
        "h1",
        { className: "demo-title" },
        i18n.t(copy["demo_copy-Title"]),
      ),
      createElement(
        "p",
        { className: "demo-body" },
        i18n.t(copy["demo_copy-Body"]),
      ),
      createElement(
        "section",
        { className: "demo-messages", "aria-live": "polite" },
        createElement(
          "p",
          { className: "demo-message" },
          i18n.t(copy.greeting, { name: "Rina" }),
        ),
        createElement(
          "p",
          { className: "demo-message" },
          i18n.t(copy.inbox, { count: 3 }),
        ),
      ),
      createElement(
        "div",
        { className: "demo-controls" },
        createElement(
          "p",
          { className: "demo-locale" },
          i18n.t(copy.locale_status, { locale: i18n.locale }),
        ),
        createElement(
          "button",
          {
            className: "demo-button",
            disabled: i18n.pending,
            onClick: () => {
              void i18n.setLocale(i18n.locale === "fr" ? "en" : "fr");
            },
            type: "button",
          },
          i18n.t(copy["demo_copy-SwitchLocale"]),
        ),
      ),
    ),
  );
}

const root = document.querySelector<HTMLElement>("#root");
if (root === null) {
  throw new Error("React demo root is missing");
}

createRoot(root).render(
  createElement(
    I18nProvider,
    { runtime, initial },
    createElement(Demo),
  ),
);
